START_OF_SEQUENCE_TOKEN = "<SOS>"
END_OF_SEQUENCE_TOKEN = "<EOS>"
UNKNOWN_TOKEN = "<UNK>"
PADDING_TOKEN = "<PAD>"
BARLINE_TOKEN = "<BARLINE>"

CONST_TOKENS = (START_OF_SEQUENCE_TOKEN, END_OF_SEQUENCE_TOKEN, UNKNOWN_TOKEN, PADDING_TOKEN, BARLINE_TOKEN)